"""Feature-doc metadata consistency (Phase 6.2).

`CORE33_META` (src/registry.rs, exposed via `describe_feature`) must agree
with observable behavior: every core33 feature carries definition/min_length/
nan_when, and a series of length min_length-1 is NaN for that feature
whenever min_length > 1. docs/features.md itself is regenerated by
tools/gen_feature_docs.py (CI checks with --check); this test also asserts
the checked-in file lists all 33 names in frozen order.
"""

from pathlib import Path

import numpy as np

import kymora

NAMES = kymora.feature_names()
REPO = Path(__file__).resolve().parents[1]


def test_every_core33_feature_has_doc_metadata():
    for name in NAMES:
        desc = kymora.describe_feature(name)
        for key in ("definition", "min_length", "nan_when", "cost", "needs"):
            assert desc.get(key), f"{name} missing {key}"
        assert int(desc["min_length"]) >= 1, name


def test_min_length_matches_observed_nan():
    rng = np.random.default_rng(0)
    for name in NAMES:
        min_len = int(kymora.describe_feature(name)["min_length"])
        if min_len <= 1:
            continue
        # Length min_len-1 on generic random data: must be NaN (not just
        # sometimes — the contract says "shorter input yields NaN").
        x = np.ascontiguousarray(rng.standard_normal(min_len - 1))
        got = kymora.extract_features(x[None, :], features=[name])[0, 0]
        assert np.isnan(got), f"{name}: length {min_len - 1} should be NaN"


def test_checked_in_features_md_lists_all_names_in_order():
    text = (REPO / "docs" / "features.md").read_text(encoding="utf-8")
    positions = [text.index(f"`{name}`") for name in NAMES]
    assert positions == sorted(positions), "feature order drifted in docs"
    assert len(NAMES) == 33
