#!/usr/bin/env python3
"""Generate docs/features.md from the built library (Phase 6.2).

Single source of truth: `feature_names()` for order, `describe_feature()`
for definition/min_length/nan_when/cost/needs/aliases (from
`CORE33_META` in src/registry.rs), and benchmarks/agreement/feature_map.json
for numpy/tsfresh/TSFEL/catch22 equivalents. Hand-editing the generated
tables is pointless: CI regenerates and diffs.

Usage:
    python tools/gen_feature_docs.py [--check]
--check exits 1 when the checked-in docs/features.md differs (CI gate).
"""

from __future__ import annotations

import difflib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DOC = REPO / "docs" / "features.md"
FEATURE_MAP = REPO / "benchmarks" / "agreement" / "feature_map.json"


def _equiv(entry: dict, lib: str) -> str:
    val = entry.get(lib)
    if val is None:
        return "—"
    return f"`{val}`"


def generate() -> str:
    import kymora

    names = kymora.feature_names()
    assert len(names) == 33, f"core33 frozen at 33, got {len(names)}"
    fmap = json.loads(FEATURE_MAP.read_text(encoding="utf-8"))["features"]

    lines = [
        "# Feature Reference",
        "",
        "<!-- GENERATED by tools/gen_feature_docs.py from the built library.",
        "     Do not hand-edit the tables; change CORE33_META in src/registry.rs",
        "     (or feature_map.json for equivalents) and regenerate. -->",
        "",
        "33 features in frozen column order. `n` = series length, `m` = mean,",
        "`s` = population std (ddof=0), `d = diff(x)`. NaN semantics follow",
        "[Numerics and NaN policy](numerics.md): `min_length` is the shortest",
        "defined length, `nan_when` lists the other undefined conditions.",
        "",
        "| # | Feature | Definition | Min length | NaN when | numpy / tsfresh / TSFEL / catch22 |",
        "|---:|---|---|---|---|---|",
    ]
    for i, name in enumerate(names):
        desc = kymora.describe_feature(name)
        fm = fmap.get(name, {})
        equiv = " / ".join(
            [
                _equiv(fm, "numpy_reference"),
                _equiv(fm, "tsfresh"),
                _equiv(fm, "tsfel"),
                _equiv(fm, "catch22"),
            ]
        )
        lines.append(
            f"| {i} | `{name}` | {desc['definition']} | {desc['min_length']} "
            f"| {desc['nan_when']} | {equiv} |"
        )
    lines += [
        "",
        "Cost classes: `A` fused reductions, `B` order statistics, `C` spectral/FFT,",
        "`D` autocorrelations. Intermediates (`needs`) show shared computation.",
        "",
        "| # | Feature | Cost | Needs | Aliases |",
        "|---:|---|---|---|---|",
    ]
    for i, name in enumerate(names):
        desc = kymora.describe_feature(name)
        aliases = desc["aliases"] or "—"
        lines.append(
            f"| {i} | `{name}` | {desc['cost']} | {desc['needs']} | {aliases} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = generate()
    if "--check" in sys.argv:
        current = DOC.read_text(encoding="utf-8")
        if current != text:
            diff = "".join(
                difflib.unified_diff(
                    current.splitlines(True), text.splitlines(True),
                    "docs/features.md", "generated",
                )
            )
            print("docs/features.md is stale; run python tools/gen_feature_docs.py")
            print(diff[:4000])
            return 1
        print("docs/features.md is current")
        return 0
    DOC.write_text(text, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
