import { FeatureDefinition } from './types';

export const FEATURES: FeatureDefinition[] = [
  {
    index: 0,
    name: 'mean',
    group: 'Stats',
    definition: 'sum(x) / n',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Population mean, computed in pass 1 accumulation.',
  },
  {
    index: 1,
    name: 'std',
    group: 'Stats',
    definition: 'sqrt(var)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Population standard deviation (ddof=0). Forced to 0.0 for exact-constant series.',
  },
  {
    index: 2,
    name: 'var',
    group: 'Stats',
    definition: 'sum((x - mean)^2) / n',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Population variance (ddof=0). Sum rounding noise suppressed on constant inputs.',
  },
  {
    index: 3,
    name: 'min',
    group: 'Stats',
    definition: 'min(x)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Smallest value in the series, tracked during pass 1.',
  },
  {
    index: 4,
    name: 'max',
    group: 'Stats',
    definition: 'max(x)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Largest value in the series, tracked during pass 1.',
  },
  {
    index: 5,
    name: 'median',
    group: 'Stats',
    definition: '50th percentile',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Numpy-default linear interpolation, partitioned via select_nth_unstable_by.',
  },
  {
    index: 6,
    name: 'quantile_10',
    group: 'Stats',
    definition: '10th percentile',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Numpy-default linear interpolation.',
  },
  {
    index: 7,
    name: 'quantile_25',
    group: 'Stats',
    definition: '25th percentile (Q1)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Numpy-default linear interpolation.',
  },
  {
    index: 8,
    name: 'quantile_75',
    group: 'Stats',
    definition: '75th percentile (Q3)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Numpy-default linear interpolation.',
  },
  {
    index: 9,
    name: 'quantile_90',
    group: 'Stats',
    definition: '90th percentile',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Numpy-default linear interpolation.',
  },
  {
    index: 10,
    name: 'skewness',
    group: 'Stats',
    definition: 'm3 / (std^3)',
    complexity: 'O(n)',
    undefinedWhen: 'std == 0 (constant series)',
    notes: 'Third standardized moment. Matches scipy.stats.skew with bias=True.',
  },
  {
    index: 11,
    name: 'kurtosis',
    group: 'Stats',
    definition: '(m4 / (var^2)) - 3',
    complexity: 'O(n)',
    undefinedWhen: 'std == 0 (constant series)',
    notes: 'Fisher excess kurtosis (Gaussian ≈ 0). Matches scipy.stats.kurtosis with bias=True.',
  },
  {
    index: 12,
    name: 'abs_energy',
    group: 'Stats',
    definition: 'sum(x^2)',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Total signal energy / sum of squared amplitudes.',
  },
  {
    index: 13,
    name: 'root_mean_square',
    group: 'Stats',
    definition: 'sqrt(mean(x^2))',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Quadratic mean / RMS amplitude.',
  },
  {
    index: 14,
    name: 'mean_abs_change',
    group: 'Change',
    definition: 'mean(|x[i+1] - x[i]|)',
    complexity: 'O(n)',
    undefinedWhen: 'n < 2',
    notes: 'Mean absolute successive first-order differences.',
  },
  {
    index: 15,
    name: 'mean_change',
    group: 'Change',
    definition: '(x[n-1] - x[0]) / (n - 1)',
    complexity: 'O(1)',
    undefinedWhen: 'n < 2',
    notes: 'Telescoping average first difference across the full series.',
  },
  {
    index: 16,
    name: 'cid_ce',
    group: 'Change',
    definition: 'sqrt(sum(((x[i+1] - x[i]) / std)^2))',
    complexity: 'O(n)',
    undefinedWhen: 'n < 2',
    notes: 'Complexity estimate on z-normalized series. Exactly 0 for constant series.',
  },
  {
    index: 17,
    name: 'mean_second_derivative_central',
    group: 'Change',
    definition: 'sum(x[i+1] - 2*x[i] + x[i-1]) / (2 * (n - 2))',
    complexity: 'O(n)',
    undefinedWhen: 'n < 3',
    notes: 'Central difference second derivative average over 3-element sliding windows.',
  },
  {
    index: 18,
    name: 'zero_crossings',
    group: 'Counts',
    definition: 'count(i: (x[i] > 0) != (x[i+1] > 0))',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Number of baseline zero-crossings. Returned as float64.',
  },
  {
    index: 19,
    name: 'mean_crossings',
    group: 'Counts',
    definition: 'count(i: (x[i] > mean) != (x[i+1] > mean))',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Number of level-crossings about the calculated series mean. Returned as float64.',
  },
  {
    index: 20,
    name: 'number_of_peaks',
    group: 'Counts',
    definition: 'count(peaks with support 3)',
    complexity: 'O(n)',
    undefinedWhen: 'never (0 when n <= 6)',
    notes: 'Samples strictly exceeding all 3 neighbors left and right. Branchless comparison.',
  },
  {
    index: 21,
    name: 'longest_strike_above_mean',
    group: 'Counts',
    definition: 'max consecutive run of x[i] > mean',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Longest unbroken sequence above the series mean. Returned as float64.',
  },
  {
    index: 22,
    name: 'longest_strike_below_mean',
    group: 'Counts',
    definition: 'max consecutive run of x[i] < mean',
    complexity: 'O(n)',
    undefinedWhen: 'never',
    notes: 'Longest unbroken sequence below the series mean. Returned as float64.',
  },
  {
    index: 23,
    name: 'autocorr_lag_1',
    group: 'Correlation',
    definition: 'autocorr(x, lag=1)',
    complexity: 'O(n)',
    undefinedWhen: 'n <= 1 or constant series',
    notes: 'Normalized sample autocorrelation at lag k = 1.',
  },
  {
    index: 24,
    name: 'autocorr_lag_2',
    group: 'Correlation',
    definition: 'autocorr(x, lag=2)',
    complexity: 'O(n)',
    undefinedWhen: 'n <= 2 or constant series',
    notes: 'Normalized sample autocorrelation at lag k = 2.',
  },
  {
    index: 25,
    name: 'autocorr_lag_5',
    group: 'Correlation',
    definition: 'autocorr(x, lag=5)',
    complexity: 'O(n)',
    undefinedWhen: 'n <= 5 or constant series',
    notes: 'Normalized sample autocorrelation at lag k = 5.',
  },
  {
    index: 26,
    name: 'autocorr_lag_10',
    group: 'Correlation',
    definition: 'autocorr(x, lag=10)',
    complexity: 'O(n)',
    undefinedWhen: 'n <= 10 or constant series',
    notes: 'Normalized sample autocorrelation at lag k = 10.',
  },
  {
    index: 27,
    name: 'trend_slope',
    group: 'Correlation',
    definition: 'OLS slope against time index 0..n-1',
    complexity: 'O(n)',
    undefinedWhen: 'n < 2',
    notes: 'Ordinary least squares trend slope. Exactly 0 for constant series.',
  },
  {
    index: 28,
    name: 'trend_r2',
    group: 'Correlation',
    definition: 'r^2 of linear trend fit',
    complexity: 'O(n)',
    undefinedWhen: 'n < 2 or constant series',
    notes: 'Coefficient of determination for the linear time trend.',
  },
  {
    index: 29,
    name: 'permutation_entropy',
    group: 'Entropy',
    definition: 'Bandt-Pompe order 3, normalized',
    complexity: 'O(n)',
    undefinedWhen: 'n < 3',
    notes: 'Shannon entropy of ordinal patterns of length 3, normalized by log(6) to [0, 1]. Branchless lookup.',
  },
  {
    index: 30,
    name: 'dominant_frequency',
    group: 'Spectral',
    definition: 'argmax_f |FFT(x)[f]|^2',
    complexity: 'O(n log n)',
    undefinedWhen: 'n < 2, constant series, or zero total power',
    notes: 'Frequency of strongest positive bin in cycles/sample (0, 0.5]. DC excluded.',
  },
  {
    index: 31,
    name: 'spectral_centroid',
    group: 'Spectral',
    definition: 'sum(f * P(f)) / sum(P(f))',
    complexity: 'O(n log n)',
    undefinedWhen: 'n < 2, constant series, or zero total power',
    notes: 'Power-weighted mean frequency across positive non-DC bins. Real FFT via realfft.',
  },
  {
    index: 32,
    name: 'spectral_entropy',
    group: 'Spectral',
    definition: '-sum(p * log(p)) / log(n_bins)',
    complexity: 'O(n log n)',
    undefinedWhen: 'n < 2, constant series, or zero total power',
    notes: 'Shannon entropy of normalized power distribution. Exactly 0 if single frequency bin.',
  },
];
